events { worker_connections 1024; }

http {
    include       /etc/nginx/conf.d/*.conf;

    server {
        listen 80 default_server;
        server_name _;

        location /dashboard {
            proxy_pass http://172.17.0.1:8080/dashboard;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location ~ ^/envs {
            proxy_pass http://172.17.0.1:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location / {
            return 200 '{"status":"DevOps Sandbox Platform","message":"Use /env-<id>/ to reach an environment"}';
            add_header Content-Type application/json;
        }
    }
}
